### ISSUE TITLE
create command-line interface utility

### ISSUE THREAD

**Issue by viict** [pentagramacs/mantis2gitlab-php#1]
This would be useful to avoid a few settings as configuration like projects, access token, username and password

**Comment by zhanglei0110** [comment]
Hello, I am a Chinese beginner, I have successfully configured mantis by myself, and I have ready-made gitlab here, which are respectively on two servers.I look at your installation configuration file, and I find that I need to configure configs/*.php's three files, but I am very confused, I do not know how to configure, and how to start after the configuration, because your bin directory has a startup program, do I need the PHP environment below
[] : PHP mantis2gitlab
Or do I change my name to mantis2gitlab.php?
If you can help me, I will be your Chinese friend, thank you

**Comment by viict** [comment]
@zhanglei0110 hello.

It's been quite sometime I last used this utility, if you find any problem feel free to raise a new issue or a new merge request.

To run the utility, as of now, you don't need to configure the `configs/*.php` files.. They're there just for reference.
What you do is install it using composer (from https://getcomposer.org/) as a global package:

`composer global require pentagramacs/mantis2gitlab-php`

After running that, you have to make sure you have COMPOSER_BIN in your path, something like this in your `.profile` or `.bashrc`:

```PATH="$HOME/.composer/vendor/bin:$PATH"```

> If you are running on windows I would rather clone the repository and `composer install` in that folder to run the `bin/mantis2gitlab` script

With that said, you just have to pass in the correct parameters to the script, that would be the following:

- `gitlab.endpoint` - Gitlab endpoint to use (https://gitlab.domain.com)
- `gitlab.access_token` - An gitlab access token fetched from (https://gitlab.domain.com/profile/personal_access_tokens)
- `gitlab.project` - An gitlab project ID or path (like group/project_name)
- `mantis.wsdl` - The WSDL for the MantisBT API (like https://mantisbt.domain.com/api/soap/mantisconnect.php?wsdl)
- `mantis.username` - Mantis user name (not all permissions is required but I recommend a administration account)
- `mantis.password` - Mantis user password
- `mantis.project` - The mantis project to fetch data from (can be the ID or the name);

You can then run:

```mantis2gitlab --gitlab.endpoint https://... --gitlab.access_token ... `test` ``` To test the communication with both sides.

And change `test` to `migrate` when ready to roll out (the migrate command also has a `--dry-run` parameter)

If you want to do some label configuration, users and stuff you _HAVE_ to clone the repository to change the `configs/*.php` files, in that case, just clone/download the repository and do your changes.

Hope this helps you. If you need anymore help just leave a message.
