### ISSUE TITLE
Error shows when testing mantis connection

### ISSUE THREAD

**Issue by sijomc** [pentagramacs/mantis2gitlab-php#6]
When executing the mantis2gitlab command, following error shows:

/opt/mantis2gitlab-php/bin# ./mantis2gitlab  test:mantis
PHP Catchable fatal error:  Argument 1 passed to M2G\Mantis::__construct() must be of the type array, null given, called in /opt/mantis2gitlab-php/src/Command/TestMantisCommand.php on line 31 and defined in /opt/mantis2gitlab-php/src/Mantis.php on line 13

Please help me to solve the issue. Thanks in advance.

**Comment by viict** [comment]
@sijomc hi! thanks for using our tool.

From what I've seen you must set the parameters to test the connections.
`bin/mantis2gitlab test:mantis --help`

Or you may also set it at the config folder making a copy of the mantis.php.template to mantis.php and setting the correct data there.

I will also update the README.md to reflect this.
